project_name: GoNetSim
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gonetsim
    main: ./cmd/gonetsim
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X github.com/lachlanharrisdev/gonetsim/cmd.Version={{.Version}}
      - -X github.com/lachlanharrisdev/gonetsim/cmd.Revision={{.ShortCommit}}
      - -X github.com/lachlanharrisdev/gonetsim/cmd.Date={{.Date}}

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  abbrev: 7
  groups:
    - title: "Features"
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: "Bug Fixes"
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: "Uncategorized"
      order: 999
  filters:
    exclude:
      - '^docs(\(.+\))?:'
      - '^test(\(.+\))?:'
      - '^refactor(\(.+\))?:'
      - '^chore(\(.+\))?:'

release:
  github:
    owner: lachlanharrisdev
    name: gonetsim
  draft: false
  replace_existing_draft: false
  use_existing_draft: false
  replace_existing_artifacts: false

  name_template: "{{ .Tag }}"
  header: |
    # GoNetSim {{ .Version }}

    **Release Date:** {{ .Date }}
    **Latest Included Commit:** {{ .ShortCommit }}
    **Download URL:** {{ .ReleaseURL }}

    ---
  footer: |
    ---

    ## Resources

    - [Documentation](https://gonetsim.lachlanharris.au/)
    - [Report Issues](https://github.com/{{ .Env.GITHUB_REPOSITORY }}/issues)