defaultBaseImage: gcr.io/distroless/base-debian12

defaultPlatforms:
  - linux/amd64
  - linux/arm64

builds:
  - id: gonetsim
    dir: .
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
