services:
  gonetsim:
    # build locally with `KO_DOCKER_REPO=gonetsim ko build --local --bare --tags=dev .`
    # then set image: gonetsim:dev
    image: ghcr.io/lachlanharrisdev/gonetsim:latest
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
      - "8080:80"
      - "8443:443"
    # volumes:
    #   - ../gonetsim.toml:/etc/gonetsim/gonetsim.toml:ro
    #   - ../handlers:/etc/gonetsim/handlers:ro
    #   - ./captures:/root/.local/share/gonetsim/runs
