name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Install Go
      id: setup-go
      uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"
    - name: Download Go modules
      shell: bash
      if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
      run: go mod download
    - name: Download Syft
      uses: anchore/sbom-action/download-syft@v0
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v7
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # After GoReleaser runs, attest all the files in ./dist/checksums.txt:
    - uses: actions/attest@v4
      with:
        subject-checksums: ./dist/checksums.txt
